require("duhl.packer")
require("duhl.gset")
require("duhl.cmp")
require("duhl.null-ls")
require("duhl.lspconfig")
-- require("duhl.ls-eslint")
-- require("duhl.ls-typescript")
require("duhl.ls-prettier")
require("duhl.set")
require("duhl.nvim-tree")
require("duhl.autotag")
require("duhl.autocmd")
require("duhl.remap")

